[pytest]
addopts = -s -v
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers=
    users: Marker for tests related to users.
    courses: Marker for tests related to courses.
    exercises: Marker for tests related to exercises.
    files: Marker for tests related to files.
    regression: Marker for regression tests.
    authentication: Marker for authentication tests.